### ISSUE TITLE
Problem wit username

### ISSUE THREAD

**Issue by JorgeosorioDev** [rzlyp/instagram-scraping#16] opened 2020-06-08 19:45 UTC
Hello, thsi method, doesnt work>

// using username for scraping
ig.scrapeUserPage('jscmila').then(result => {
  console.dir(result);
});

Any Idea, how to solve?

**Comment by gianpaj** [comment] 2020-10-24 23:19
what error do you get?

**Comment by gianpaj** [comment] 2020-10-24 23:45
Duplicate of #17

**Closed as completed by gianpaj** 2020-10-24 23:45 UTC
